name: Execute unit tests when pushing to main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up unit test script permissions
      run: chmod +x project/tests.sh

    - name: Run unit tests
      env: 
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_API_KEY }}
      run: bash ./project/tests.sh 